### ISSUE TITLE
Excessive Type Errors in logs after v1.2.0 Release

### ISSUE THREAD

**Issue by jonato1** [fjs21/homebridge-blueair#265]
Example of error: 
`[4/13/2023, 7:35:46 PM] [@fjs21/homebridge-blueair] TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at BlueAirDustProtectAccessory.updateLED (/homebridge/node_modules/@fjs21/homebridge-blueair/src/platformAccessory_DustProtect.ts:553:22)
    at BlueAirDustProtectAccessory.updateAccessoryCharacteristics (/homebridge/node_modules/@fjs21/homebridge-blueair/src/platformAccessory_DustProtect.ts:354:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlueAirDustProtectAccessory.handleAirPurifierActiveGet (/homebridge/node_modules/@fjs21/homebridge-blueair/src/platformAccessory_DustProtect.ts:258:5)
[4/13/2023, 7:35:46 PM] [@fjs21/homebridge-blueair] This plugin threw an error from the characteristic 'Active': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'updateCharacteristic'). See https://homebridge.io/w/JtMGR for more info.
`

**Comment by jonato1** [comment]
Errors are persisting for the following characteristics:

- 'Current Air Purifier State'
- 'Active'
- 'Rotation Speed'
- 'Target Air Purifier State'
- 'Lock Physical Controls'
- 'On'

[4/15/2023, 10:16:26 AM] [@fjs21/homebridge-blueair] This plugin threw an error from the characteristic 'Current Air Purifier State': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'updateCharacteristic'). See https://homebridge.io/w/JtMGR for more info.
[4/15/2023, 10:16:27 AM] [@fjs21/homebridge-blueair] This plugin threw an error from the characteristic 'Active': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'updateCharacteristic'). See https://homebridge.io/w/JtMGR for more info.
[4/15/2023, 10:16:27 AM] [@fjs21/homebridge-blueair] This plugin threw an error from the characteristic 'Rotation Speed': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'updateCharacteristic'). See https://homebridge.io/w/JtMGR for more info.
[4/15/2023, 10:16:27 AM] [@fjs21/homebridge-blueair] This plugin threw an error from the characteristic 'Target Air Purifier State': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'updateCharacteristic'). See https://homebridge.io/w/JtMGR for more info.
[4/15/2023, 10:16:27 AM] [@fjs21/homebridge-blueair] This plugin threw an error from the characteristic 'Lock Physical Controls': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'updateCharacteristic'). See https://homebridge.io/w/JtMGR for more info.
[4/15/2023, 10:16:27 AM] [@fjs21/homebridge-blueair] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'updateCharacteristic'). See https://homebridge.io/w/JtMGR for more info.

**Comment by jonato1** [comment]
Resolved with https://github.com/fjs21/homebridge-blueair/commit/1a05875d8deb894ae68dc5edab81116f2ccba5a5
