### ISSUE TITLE
Add Support for Classic 480i / Classic 490i

### ISSUE THREAD

**Issue by jonato1** [fjs21/homebridge-blueair#331]
Originally requested by @kjohn [here](https://github.com/fjs21/homebridge-blueair/issues/6#issuecomment-1584214236):

 > I see you have added compatibility for the Classic 680i / Classic 690i. Could you please add compatibility for the Classic 480i / Classic 490i? Thank you.
> 
> [08/06/2023, 23:01:24] [@fjs21/homebridge-blueair] Restoring existing accessory from cache: Office [08/06/2023, 23:01:25] [@fjs21/homebridge-blueair] Office of type "classic_490i" initialized. [08/06/2023, 23:01:25] [@fjs21/homebridge-blueair] Restoring existing accessory from cache: Guest Bedroom [08/06/2023, 23:01:25] [@fjs21/homebridge-blueair] Office: device type not recognized, contact developer via GitHub. [08/06/2023, 23:01:25] [@fjs21/homebridge-blueair] classic_490i: compatibility type not recognized.

**Comment by jonato1** [comment]
@kjohn - It looks like there was already support for 480i; I have added support for 490i (and 690i since that seemed to be unsupported too). I can't test it since I don't have these models, so when the next release comes out, please let me know if you see any issues.

**Comment by jonato1** [comment]
This will be released with v1.3.0 shortly.

**Comment by kjohn** [comment]
It appears to be stuck in a loop due to a type error due to the LED. By unselecting the Hide LED option, it resolves this issue. Thank you so much for your hard effort! 

Here is my log: 

[15/07/2023, 10:00:56] [@fjs21/homebridge-blueair] Launched child bridge with PID 1411
[15/07/2023, 10:00:58] Registering platform '@fjs21/homebridge-blueair.BlueAir'
[15/07/2023, 10:00:58] [@fjs21/homebridge-blueair] Loaded @fjs21/homebridge-blueair v1.3.1 child bridge successfully
[15/07/2023, 10:00:58] Loaded 4 cached accessories from cachedAccessories.0ED5A55EF1C5.
[15/07/2023, 10:00:58] [@fjs21/homebridge-blueair] base_API_url: https://api.blueair.io/v2/user/mrjohn@gmail.com/homehost/
[15/07/2023, 10:00:58] [@fjs21/homebridge-blueair] Loading accessory from cache: Master Bedroom 
[15/07/2023, 10:00:58] [@fjs21/homebridge-blueair] Loading accessory from cache: Baby Room
[15/07/2023, 10:00:58] [@fjs21/homebridge-blueair] Loading accessory from cache: Office
[15/07/2023, 10:00:58] [@fjs21/homebridge-blueair] Loading accessory from cache: Guest Bedroom
[15/07/2023, 10:00:59] Homebridge v1.6.1 (HAP v0.11.1) (@fjs21/homebridge-blueair) is running on port 55148.
[15/07/2023, 10:01:00] [@fjs21/homebridge-blueair] Got homehost: api-us-east-1.blueair.io
[15/07/2023, 10:01:01] [@fjs21/homebridge-blueair] x-auth-token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im1yam9obkBnbWFpbC5jb20iLCJqdGkiOiJkZjM2ZjAyNC05NWEyLTRjNTUtYWNjZC1mYTk2M2NhNjFmZWUiLCJleHAiOjE3MjA5MjYwNjE1NjQsImV4cGlyYXRpb25EYXRlIjoxNzIwOTI2MDYxNTY0fQ.As26IhiKYKIN2UpPg18DYUrd5zaZDqAaujIycF6Py2w
[15/07/2023, 10:01:02] [@fjs21/homebridge-blueair] Found 4 devices.
[15/07/2023, 10:01:02] [@fjs21/homebridge-blueair] Restoring existing accessory from cache: Master Bedroom 
[15/07/2023, 10:01:03] [@fjs21/homebridge-blueair] Master Bedroom  of type "sense+" initialized.
[15/07/2023, 10:01:03] [@fjs21/homebridge-blueair] Removing stale Service: uuid:[00000043-0000-1000-8000-0026BB765291]
[15/07/2023, 10:01:03] [@fjs21/homebridge-blueair] Restoring existing accessory from cache: Baby Room
[15/07/2023, 10:01:04] [@fjs21/homebridge-blueair] Baby Room of type "classic_490i" initialized.
[15/07/2023, 10:01:04] [@fjs21/homebridge-blueair] Removing stale Service: uuid:[00000043-0000-1000-8000-0026BB765291]
[15/07/2023, 10:01:04] [@fjs21/homebridge-blueair] Restoring existing accessory from cache: Office
[15/07/2023, 10:01:06] [@fjs21/homebridge-blueair] Office of type "classic_490i" initialized.
[15/07/2023, 10:01:06] [@fjs21/homebridge-blueair] Removing stale Service: uuid:[00000043-0000-1000-8000-0026BB765291]
[15/07/2023, 10:01:06] [@fjs21/homebridge-blueair] Restoring existing accessory from cache: Guest Bedroom
[15/07/2023, 10:01:06] [@fjs21/homebridge-blueair] Guest Bedroom of type "classic_490i" initialized.
[15/07/2023, 10:01:06] [@fjs21/homebridge-blueair] Removing stale Service: uuid:[00000043-0000-1000-8000-0026BB765291]
[15/07/2023, 10:01:12] [@fjs21/homebridge-blueair] This plugin generated a warning from the characteristic 'PM2.5 Density': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[15/07/2023, 10:01:12] [@fjs21/homebridge-blueair] This plugin generated a warning from the characteristic 'VOC Density': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[15/07/2023, 10:01:12] [@fjs21/homebridge-blueair] This plugin generated a warning from the characteristic 'Air Quality': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[15/07/2023, 10:01:12] [@fjs21/homebridge-blueair] This plugin generated a warning from the characteristic 'Current Relative Humidity': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[15/07/2023, 10:01:12] [@fjs21/homebridge-blueair] This plugin generated a warning from the characteristic 'Carbon Dioxide Detected': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at BlueAirPlatformAccessory.updateLED (/usr/local/lib/node_modules/@fjs21/homebridge-blueair/src/platformAccessory.ts:542:24)
    at BlueAirPlatformAccessory.updateAccessoryCharacteristics (/usr/local/lib/node_modules/@fjs21/homebridge-blueair/src/platformAccessory.ts:360:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[15/07/2023, 10:01:13] [@fjs21/homebridge-blueair] Child bridge process ended
[15/07/2023, 10:01:13] [@fjs21/homebridge-blueair] Process Ended. Code: 1, Signal: null
[15/07/2023, 10:01:20] [@fjs21/homebridge-blueair] Restarting Process...
[15/07/2023, 10:01:21] [@fjs21/homebridge-blueair] Launched child bridge with PID 1441
[15/07/2023, 10:01:23] Registering platform '@fjs21/homebridge-blueair.BlueAir'
[15/07/2023, 10:01:23] [@fjs21/homebridge-blueair] Loaded @fjs21/homebridge-blueair v1.3.1 child bridge successfully
[15/07/2023, 10:01:23] Loaded 4 cached accessories from cachedAccessories.0ED5A55EF1C5.
[15/07/2023, 10:01:23] [@fjs21/homebridge-blueair] base_API_url: https://api.blueair.io/v2/user/mrjohn@gmail.com/homehost/
[15/07/2023, 10:01:23] [@fjs21/homebridge-blueair] Loading accessory from cache: Master Bedroom 
[15/07/2023, 10:01:23] [@fjs21/homebridge-blueair] Loading accessory from cache: Baby Room
[15/07/2023, 10:01:23] [@fjs21/homebridge-blueair] Loading accessory from cache: Office
[15/07/2023, 10:01:23] [@fjs21/homebridge-blueair] Loading accessory from cache: Guest Bedroom
[15/07/2023, 10:01:23] Homebridge v1.6.1 (HAP v0.11.1) (@fjs21/homebridge-blueair) is running on port 55148.
[15/07/2023, 10:01:24] [@fjs21/homebridge-blueair] Got homehost: api-us-east-1.blueair.io
[15/07/2023, 10:01:26] [@fjs21/homebridge-blueair] x-auth-token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im1yam9obkBnbWFpbC5jb20iLCJqdGkiOiI5OTYyYzMyYi0yNDVhLTQ3ZmEtYjUzMS01YTNhODViMzQxZTYiLCJleHAiOjE3MjA5MjYwODYyNTAsImV4cGlyYXRpb25EYXRlIjoxNzIwOTI2MDg2MjUwfQ.zG8ukqArevda-MjMnncFFog1VbXwx2n-ywmAOt13XSc
[15/07/2023, 10:01:27] [@fjs21/homebridge-blueair] Found 4 devices.
[15/07/2023, 10:01:27] [@fjs21/homebridge-blueair] Restoring existing accessory from cache: Master Bedroom 
[15/07/2023, 10:01:28] [@fjs21/homebridge-blueair] Master Bedroom  of type "sense+" initialized.
[15/07/2023, 10:01:28] [@fjs21/homebridge-blueair] Removing stale Service: uuid:[00000043-0000-1000-8000-0026BB765291]
[15/07/2023, 10:01:28] [@fjs21/homebridge-blueair] Restoring existing accessory from cache: Baby Room
[15/07/2023, 10:01:29] [@fjs21/homebridge-blueair] Baby Room of type "classic_490i" initialized.
[15/07/2023, 10:01:29] [@fjs21/homebridge-blueair] Removing stale Service: uuid:[00000043-0000-1000-8000-0026BB765291]
[15/07/2023, 10:01:29] [@fjs21/homebridge-blueair] Restoring existing accessory from cache: Office
[15/07/2023, 10:01:30] [@fjs21/homebridge-blueair] Office of type "classic_490i" initialized.
[15/07/2023, 10:01:30] [@fjs21/homebridge-blueair] Removing stale Service: uuid:[00000043-0000-1000-8000-0026BB765291]
[15/07/2023, 10:01:30] [@fjs21/homebridge-blueair] Restoring existing accessory from cache: Guest Bedroom
[15/07/2023, 10:01:31] [@fjs21/homebridge-blueair] Guest Bedroom of type "classic_490i" initialized.
[15/07/2023, 10:01:31] [@fjs21/homebridge-blueair] Removing stale Service: uuid:[00000043-0000-1000-8000-0026BB765291]
[15/07/2023, 10:01:37] [@fjs21/homebridge-blueair] This plugin generated a warning from the characteristic 'PM2.5 Density': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[15/07/2023, 10:01:37] [@fjs21/homebridge-blueair] This plugin generated a warning from the characteristic 'VOC Density': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[15/07/2023, 10:01:37] [@fjs21/homebridge-blueair] This plugin generated a warning from the characteristic 'Air Quality': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[15/07/2023, 10:01:37] [@fjs21/homebridge-blueair] This plugin generated a warning from the characteristic 'Current Relative Humidity': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[15/07/2023, 10:01:37] [@fjs21/homebridge-blueair] This plugin generated a warning from the characteristic 'Carbon Dioxide Detected': Characteristic not in required or optional characteristic section for service AirPurifier. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at BlueAirPlatformAccessory.updateLED (/usr/local/lib/node_modules/@fjs21/homebridge-blueair/src/platformAccessory.ts:542:24)
    at BlueAirPlatformAccessory.updateAccessoryCharacteristics (/usr/local/lib/node_modules/@fjs21/homebridge-blueair/src/platformAccessory.ts:360:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[15/07/2023, 10:01:37] [@fjs21/homebridge-blueair] Child bridge process ended
[15/07/2023, 10:01:37] [@fjs21/homebridge-blueair] Process Ended. Code: 1, Signal: null
[15/07/2023, 10:01:44] [@fjs21/homebridge-blueair] Restarting Process...
