### ISSUE TITLE
1.3.1 crashes when multiple air purifiers are found on AWS

### ISSUE THREAD

**Issue by Bubbgump209** [fjs21/homebridge-blueair#368]
```
[9/11/2023, 3:09:46 PM] [BlueAir] Found 0 devices.
[9/11/2023, 3:09:47 PM] [BlueAir] ** AWS login complete **
[9/11/2023, 3:09:48 PM] [BlueAir] Found 2 Blueair AWS-compatible devices.
[9/11/2023, 3:09:49 PM] [BlueAir] Adding new accessory: 5288f453-6e1a-412b-ac08-a10b97f327d5
[9/11/2023, 3:09:50 PM] [BlueAir] Creating new object: BlueAirDustProtectAccessory
[9/11/2023, 3:09:51 PM] [BlueAir] Adding new accessory: 5288f453-6e1a-412b-ac08-a10b97f327d5
[9/11/2023, 3:09:51 PM] Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory.addService (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:552:17)
    at PlatformAccessory.addService (/homebridge/node_modules/homebridge/src/platformAccessory.ts:98:41)
    at BlueAirDustProtectAccessory.setAccessoryInformation (/homebridge/node_modules/@fjs21/homebridge-blueair/src/platformAccessory_DustProtect.ts:188:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[9/11/2023, 3:09:51 PM] Got SIGTERM, shutting down Homebridge...
[9/11/2023, 3:09:52 PM] [BlueAir] Creating new object: BlueAirDustProtectAccessory
[9/11/2023, 3:09:54 PM] Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory.addService (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:552:17)
    at PlatformAccessory.addService (/homebridge/node_modules/homebridge/src/platformAccessory.ts:98:41)
    at BlueAirDustProtectAccessory.setAccessoryInformation (/homebridge/node_modules/@fjs21/homebridge-blueair/src/platformAccessory_DustProtect.ts:188:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[9/11/2023, 3:09:56 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

It appears the plugin is reusing a UUID for multiple devices?

**Comment by alanhartless** [comment]
I'm experiencing the same thing.  I have 3 7470i purifiers.

**Comment by alexissusset** [comment]
likewise, experiencing the same issue

**Comment by alanhartless** [comment]
I'm experiencing the same issue. 

```
[2/15/2024, 7:52:21 AM] [BlueAir] Adding new accessory: 52dd84a1-68a9-4e8d-abc3-76bcbd227547
[2/15/2024, 7:52:23 AM] [BlueAir] Creating new object: BlueAirDustProtectAccessory
[2/15/2024, 7:52:23 AM] [BlueAir] Removing stale Service: uuid:[00000043-0000-1000-8000-0026BB765291]
[2/15/2024, 7:52:24 AM] Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory.addService (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:552:17)
    at PlatformAccessory.addService (/volume1/homebridge/node_modules/homebridge/src/platformAccessory.ts:98:41)
    at BlueAirDustProtectAccessory.setAccessoryInformation (/volume1/homebridge/node_modules/@fjs21/homebridge-blueair/src/platformAccessory_DustProtect.ts:188:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2/15/2024, 7:52:24 AM] Got SIGTERM, shutting down Homebridge...
[2/15/2024, 7:52:25 AM] [BlueAir] Adding new accessory: 52dd84a1-68a9-4e8d-abc3-76bcbd227547
[2/15/2024, 7:52:26 AM] [BlueAir] Creating new object: BlueAirDustProtectAccessory
[2/15/2024, 7:52:26 AM] [BlueAir] Removing stale Service: uuid:[00000043-0000-1000-8000-0026BB765291]
[2/15/2024, 7:52:27 AM] Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory.addService (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:552:17)
    at PlatformAccessory.addService (/volume1/homebridge/node_modules/homebridge/src/platformAccessory.ts:98:41)
    at BlueAirDustProtectAccessory.setAccessoryInformation (/volume1/homebridge/node_modules/@fjs21/homebridge-blueair/src/platformAccessory_DustProtect.ts:188:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
